- database/useList.ts
- database/useListKeys.ts
- database/useListVals.ts
- database/useObject.ts
- database/useObjectVal.ts
- firestore/useCollection.ts
- firestore/useDocument.ts
- storage/useDownloadURL.ts
- util/refHooks.ts
Developing using these hooks, I've been in front of situations that references cannot be mounted at the first component execution. As explained on (https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level)[React docs], hooks cannot be called inside as an *if* statement.
To avoid this, we can pass an invalid reference to the firebase hooks. But, if you have implemented the strongest security rules, you will receive a permission denied error.
So, we need to pass references optionally to solve all of these problems.
I've already added support by this PR!
Example of usage in a container that fits authenticated or not state:
```typescript
export function useUsername() {
const { user } = useAuthState(auth)
const usernameRef = user
? …
```
> Add support of nulled references as props of hooks

- firestore/index.js.flow
The flow type declarations for the firestore module import QuerySnapshot but then try to use it as firestore.QuerySnapshot.
> Fix flow types for firestore

- firestore/helpers/index.ts
```javascript
const { value, loading, error } = useDocumentData(...);
// if the document doesn't exist, value will be {}
// this means we have to check some arbitrary property to ensure existence
if (value.someRandomProperty) {
...
}
// by returning null, we are being more explicit that the document doesn't exist
if (value) {
...
}
```
> Return null instead of empty object when document doesn't exist

- database/useList.ts
- database/useObject.ts
- firestore/useCollection.ts
- firestore/useDocument.ts
`React.memo()` will work as expected with this!
Without this, rerender (e.g. calling `setState()` of `useState()` in the render function) will cause `useCollectionData()` and `useDocumentData()` (and realtime database counter parts) to return different reference (`!==`) of data.
> Add useMemo() for value fetching hooks

- firestore/useCollection.ts
- firestore/useCollectionOnce.ts
- firestore/useDocument.ts
- firestore/useDocumentOnce.ts
Use reset instead of set value when no value is present
Should fix: https://github.com/CSFrequency/react-firebase-hooks/issues/17
> Preserve loading state

- auth/useAuthState.ts
- database/useList.ts
- database/useObject.ts
- firestore/useCollection.ts
- firestore/useCollectionOnce.ts
- firestore/useDocument.ts
- firestore/useDocumentOnce.ts
- util/useLoadingValue.ts
Avoid returning new arrays/objects when the components of said arrays/objects have not changed. This will help users avoid re-renders in their code.
> Memoize hook return

- firestore/README.md
- firestore/helpers/index.ts
- firestore/index.js.flow
- firestore/useCollection.ts
- firestore/useCollectionOnce.ts
- firestore/useDocument.ts
- firestore/useDocumentOnce.ts
As suggested in #56, this PR add the functionality to specify a 'refField'. It works similar to the existing idField and populates the specified field with the value from firebase.firestore.QuerySnapshot.ref for easy access if required.
Closes #56
> Possibility to populate the firebase.firestore.QuerySnapshot.ref field

- database/helpers/useListReducer.ts
- database/useList.ts
- package.json
1. Use the `.once`’s `val()` to determine the number of children, then batch that many calls to the `child_added` handler into one `value` dispatch, resulting in one additional render instead of one progressively slower render per child.
2. Fix shadowing of `query` variable, rename to `ref` instead.
3. Fix the `ref.off` calls to pass the right function to unsubscribe.
4. Fix dependencies on `useEffect`.
5. Fix some type references.
Fixes #74
> Improve useList efficiency

- .gitignore
- auth/README.md
- auth/index.ts
- auth/useAuthState.ts
- auth/useLogin.ts
- auth/useRegister.ts
- package-lock.json
- package.json
- util/index.ts
- util/useLoadingValue.ts
Added two new hooks for sign In and Register
1. Created a function that you can call to start the process
2.  `loading`, `credential`, `error` params provided
3.  Updated readme to show implementation of new hooks and one complete example
Should Close: #85 , close: #46 , close: #43
> Fix auth bug

- package.json
ref: #86
The firebase v8 support may make it difficult to use this hooks with earlier firebase versions.
It should be specified with the release of v3 major version.
> Add firebase v8 to peerDependencies

- auth/useSignInWithEmailAndPassword.ts
Close #121
`import 'firebase/auth';` is unnecessary and should be written in user code. It causes #121 issue.
(The current rollup settings doesn't consider `firebase/auth` as an external library, so `firebase/auth` is bundled in `react-firebase-hooks/auth`.)
> fix: remove unnecessary import statement

- firestore/types.ts
This merge request corrects the type for the new `refField` attribute from `string` to `firebase.firestore.DocumentReference<T>`.
With this update, if `refField` was set to `ref`, one can call `item.ref.collection()...` etc, and get types as expected.
> Use DocumentReference type for Data ref attribute

- firestore/helpers/index.ts
such modification breaks type casting using withConverter (fixes #128)
> Avoid DocumentData prototype overriding (#128)

- auth/useCreateUserWithEmailAndPassword.ts
I added an option to send out the email verification after successful creation. 
Let me know what you think about this.
> Add option to hook "createUserWithEmailAndPassword" for enabling email verification sendout

- database/useList.ts
Hi and thanks for the awesome library!
Couple of days ago we faced the following issue: if a new child is added after `useList` hook was called, the list is updated as expected, but at the end it has a snapshot of the whole object in its initial state instead of a new child.
For example, let's assume that a new child `4` is added.
Expected behaviour:
```
[1, 2, 3] → [1, 2, 3, 4]
```
Actual behaviour:
```
[1, 2, 3] → [1, 2, 3, {a: 1, b: 2, c: 3}]
```
First we were searching for a bug in our code, but during debugging found that it's caused just by a small mistake in `onChildAdded` call.
> fix: useList works wrong when a new child is added

- firestore/types.ts
Solution to issue #134 
This change will make the `IDOption` type included in the built types, which will allow `tsc` to understand the `DataOptions` and `OnceDataOptions` types.
This is my first Open Source contribution, so I hope I did it right :sweat_smile:
> Export `IDOption` type

- database/README.md
not a direct value like `useObjectVal` does.
> `useObject` gives a snapshot

- firestore/helpers/index.ts
> Bugfix: in "snapshotToData" helper call snapshot.exists(). It was property, now it became method after v4 update (firebase v9)

- auth/types.ts
Fix`AuthActionHooks` type from `void` to `Promise<void>`.
The type of `signInWithEmailAndPassword` and `createUserWithEmailAndPassword` are `(email: string, password: string) => Promise<void>`
But `AuthActionHooks` type is `(email: string, password: string) => void`.  so, the type of these functions is wrong, so I created this PR!
Thanks for the great library!
> Fix AuthActionHooks type from 'void' to 'Promise<void>'

- firestore/README.md
Fixed incorrect parentheses in README for firestore's useDocuments hook
> fix: Incorrect parentheses in README

- auth/README.md
Fixed incorrect arguments for `useSignInWithEmailAndPassword` hook
> Fix: Incorrect arguments in README

- auth/useAuthState.ts
Add possibility to pass options for onUserChanged, a function which is called if a user auth state changed.
This might close https://github.com/CSFrequency/react-firebase-hooks/issues/33
> add options to useAuthState hook "onUserChanged"

- firestore/useCollection.ts
- firestore/useDocument.ts
Due to results being returned asynchronously, Firestore use*Once methods are susceptible to race conditions when queries change.
This PR adds protection to ensure that setValue and setError are only called for results matching the current request.
See issue https://github.com/CSFrequency/react-firebase-hooks/issues/194 for more details.
> Adds inactive request protection to Firestore *Once methods

- functions/useHttpsCallable.ts
Considering the following line:
```typescript
const [submit] = useHttpsCallable<ContactFields, boolean>(functions, 'sendContact')
```
The return type for `submit` is `Promise<unknown>`. With this change, the return type is `Promise<HttpsCallableResult<boolean> | undefined>`
> Fix HttpsCallable return type.

- README.md
The link of v3 in older versions is not redirecting to the latest version `v3.0.5`.
> Update README.md v3 link

- firestore/README.md
There was a simple typo in the README. This change fixes it.
> Fixed typo in README

- auth/README.md
- auth/index.ts
- auth/useUpdateUser.ts
First off, thanks for this library (@chrisbianca and @CSFrequency)!
I have some code that is using `useUpdateEmail()`, but I recently learned about the [verifyBeforeUpdateEmail](https://firebase.google.com/docs/reference/js/v8/firebase.User#verifybeforeupdateemail) function (which I would prefer to use instead of [updateEmail](https://firebase.google.com/docs/reference/js/v8/firebase.User#updateemail)).
I searched this repo, and did not see any feature requests or code related to `verifyBeforeUpdateEmail` so I went ahead and added it.
I didn't do any testing, but I followed all the `useUpdateEmail/updateEmail` code- everything is very similar.
Let me know if you would like any more info!
I also fixed 1 existing typo in the readme (`addres`->`address`).
> [auth] add useVerifyBeforeUpdateEmail hook

- util/useLoadingValue.ts
I'm using `useAuthState` in my application and found it causing my component re-render infinitely, after some debugging, I noticed the problem is in `useLoadingValue`, the returned `setValue` and `setError` are changing every time it re-run. (useMemo doesn't help here). We need to use `useCallback` to prevent them from changing.
> Fix useLoadingValue perf issue
